package Cleavages::Model::Cleavages;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'Cleavages::Schema',
    
    connect_info => {
        dsn => 'dbi:Pg:dbname=cleavages',
        user => 'cleavages',
        password => '',
    }
);

=head1 NAME

Cleavages::Model::Cleavages - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Cleavages>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Cleavages::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.48

=head1 AUTHOR

Chisel

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
